# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('accel_x', models.IntegerField()),
                ('accel_y', models.IntegerField()),
                ('accel_z', models.IntegerField()),
                ('gyro_x', models.FloatField()),
                ('gyro_y', models.FloatField()),
                ('gyro_z', models.FloatField()),
                ('barometer', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
    ]
