# Generated by Django 2.0.2 on 2018-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_islive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='accel_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='accel_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='accel_z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='barometer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='gyro_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='gyro_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='gyro_z',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
