# Generated by Django 2.0.2 on 2018-04-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20180308_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='accel_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='accel_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='accel_z',
            field=models.FloatField(default=0),
        ),
    ]
