# Generated by Django 2.0.2 on 2018-04-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20180411_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeInit', models.FloatField(default=0)),
            ],
        ),
    ]
