# Generated by Django 2.0.2 on 2018-05-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_timeinit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeInit',
        ),
    ]
