# Generated by Django 2.0.2 on 2018-05-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_timeinit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
    ]
